import Layout from "~/components/Layout";
import Link from "next/link";
import Head from "next/head";
import { api } from "~/utils/api";
import Loading from "~/components/Loading";

export default function All() {
  const { data, isLoading } = api.recipe.getAllRecipeNames.useQuery();
  const allRecipes = data ?? [];

  if (isLoading) return <Loading />;

  return (
    <Layout>
      <Head>
        <title>Summarize</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {allRecipes.length === 0 ? (
        <p className="text-white">No recipes found</p>
      ) : (
        <ul className="text-xl text-white">
          {allRecipes.map((name) => (
            <li key={name} className="underline">
              <Link href={name}>{name.split("-").join(" ")}</Link>
            </li>
          ))}
        </ul>
      )}
    </Layout>
  );
}
