import Head from "next/head";
import HeaderBar from "../HeaderBar";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <Head>
        <title>Summarize</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] p-2 sm:p-4">
        <HeaderBar />
        {children}
      </main>
    </div>
  );
}
