import Head from "next/head";
import Layout from "~/components/Layout";
import Main from "~/components/Main";

export default function Home() {
  return (
    <>
      <Head>
        <title>Summarize</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Main />
      </Layout>
    </>
  );
}
