import Head from "next/head";
import HeaderBar from "~/components/HeaderBar";
import Main from "~/components/Main";

export default function Home() {
  return (
    <>
      <Head>
        <title>Summarize</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <HeaderBar />
        <Main />
      </main>
    </>
  );
}
